services:
  stats-server:
    build: ./stats/stats-server
    image: stats-server
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats
      - SPRING_DATASOURCE_USERNAME=stats
      - SPRING_DATASOURCE_PASSWORD=1234
      - STATS_SERVER_URL=http://stats-server:9090

#  stats-server:
#    build: ./stats/stats-server
#    image: stats-server
#    container_name: stats-server
#    networks:
#      - ewm-net
#    ports:
#      - "9091:9091"
#    depends_on:
#      - stats-db
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/emw-stats
#      - SPRING_DATASOURCE_USERNAME=root
#      - SPRING_DATASOURCE_PASSWORD=root
#      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
#      - SERVER_PORT=9091
#    healthcheck:
#      test: "curl --fail --silent localhost:9091/actuator/health | grep UP || exit 1"
#      timeout: 5s
#      interval: 25s
#      retries: 10

  stats-db:
    image: postgres:16.1
    container_name: stats_db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_USER=stats
      - POSTGRES_PASSWORD=stats
      - POSTGRES_DB=stats
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

#  stats-db:
#    image: postgres:16.1
#    container_name: postgres-ewm-stats_db
#    networks:
#      - ewm-net
#    ports:
#      - "6542:5432"
#    environment:
#      - POSTGRES_USER=root
#      - POSTGRES_PASSWORD=root
#      - POSTGRES_DB=ewm-stats
#    healthcheck:
#      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
#      timeout: 5s
#      interval: 10s
#      retries: 15

  ewm-service:
    build: ./core/main-service
    image: main-service
    container_name: ewm-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm
      - SPRING_DATASOURCE_USERNAME=ewm
      - SPRING_DATASOURCE_PASSWORD=1234
      - STATS_SERVER_URL=http://stats-server:9090

#  ewm-service:
#    build: ./core/main-service
#    image: main-service
#    container_name: ewm-service
#    networks:
#      - ewm-net
#    ports:
#      - "8081:8081"
#    depends_on:
#      - ewm-db
#      - eureka-client
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm-main
#      - SPRING_DATASOURCE_USERNAME=root
#      - SPRING_DATASOURCE_PASSWORD=root
#      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
#      - SERVER_PORT=8081
#    healthcheck:
#      test: "curl --fail --silent localhost:8081/actuator/health | grep UP || exit 1"
#      timeout: 5s
#      interval: 25s
#      retries: 10

  ewm-db:
    image: postgres:16.1
    container_name: ewm_db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_USER=ewm
      - POSTGRES_PASSWORD=ewm
      - POSTGRES_DB=ewm
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

#  ewm-db:
#    image: postgres:16.1
#    container_name: postgres-ewm-main-db
#    networks:
#      - ewm-net
#    ports:
#      - "6541:5432"
#    environment:
#      - POSTGRES_USER=root
#      - POSTGRES_PASSWORD=root
#      - POSTGRES_DB=ewm-main
#    healthcheck:
#      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
#      timeout: 5s
#      interval: 10s
#      retries: 15

#networks:
#  ewm-net: